export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const SIGNUP_ROUTE = '/signup'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const DEVICE_ROUTE = '/device-page'
export const CREATE_ROUTE = '/create-device'
export const ORDERS_ROUTE = '/orders'